AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  testFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: test.handler
      Runtime: nodejs20.x
      Events:
        testEvent:
          Type: Api
          Properties:
            Path: /test
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
        testOptionsEvent:
          Type: Api
          Properties:
            Path: /test
            Method: options
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
  GoogleAuthGISFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: google_auth_gis.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          JWT_SECRET: !Ref JwtSecret
      Events:
        GoogleAuthEvent:
          Type: Api
          Properties:
            Path: /auth/google_gis
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
        GoogleAuthOptionsEvent:
          Type: Api
          Properties:
            Path: /auth/google_gis
            Method: options
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
        VerifyAuthEvent:
          Type: Api
          Properties:
            Path: /auth/google_gis/verify
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
        VerifyAuthOptionsEvent:
          Type: Api
          Properties:
            Path: /auth/google_gis/verify
            Method: options
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
  GoogleAuthOAuth2Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: google_auth_oauth2.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_REDIRECT_URI: !Ref GoogleRedirectUri
          JWT_SECRET: !Ref JwtSecret
      Events:
        testGetEvent:
          Type: Api
          Properties:
            Path: /auth/google_oauth2
            Method: get
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true
        testOptionsEvent:
          Type: Api
          Properties:
            Path: /auth/google_oauth2
            Method: options
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              AllowCredentials: true

Parameters:
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
  GoogleClientSecret:
    Type: String
    Description: Google OAuth Client Secret
  GoogleRedirectUri:
    Type: String
    Description: Google OAuth Client Redirect Uri
  JwtSecret:
    Type: String
    Description: Secret key for JWT signing
    NoEcho: true